services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: bachar
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
  fullstack-api:
    container_name: fullstackApi
    image: bachard978/fullstack-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
